parameters: {}
environment: {}
packages:
    - name: yad2_fetcher
      environment: {}
      parameters: {}
      functions:
        - name: main_fetcher
          main: ""
          runtime: go:1.20
          parameters: {}
          environment: {}

